name: Deploy to FTP

on:
  workflow_run:
    workflows: ["Test Code"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies and build
        run: |
          # Replace with your actual build commands
          npm install
          npm run build

      - name: Set up FTP
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_LOGIN }}
          password: ${{ secrets.FTP_PWD }}
          server-dir: www/bca-app/ # Adjust this to your desired FTP path
          local-dir: dist/
